"use client";
import React from "react";
import Link from "next/link";
import { ChevronRight } from "lucide-react";

export const Header = () => (
  <div className="mb-6">
    <nav className="flex items-center gap-1.5 mb-3">
      <Link href="/dashboard" className="text-[11px] font-bold uppercase tracking-[0.1em] text-tertiary hover:text-foreground transition">Dashboard</Link>
      <ChevronRight size={12} className="text-tertiary" />
      <span className="text-[11px] font-bold uppercase tracking-[0.1em] text-foreground">Coupons & Dividends</span>
    </nav>
    <h1 className="text-[28px] font-extrabold tracking-[-0.05em] text-foreground leading-tight">Coupons & Dividends</h1>
    <p className="text-[13px] text-muted-foreground font-medium mt-1.5">Analyze the cash flow generated by your investments.</p>
  </div>
);
export default Header;
