"use client";

import React from "react";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { CardDescription, CardTitle } from "@/components/ui/card";

export const Header = () => (
  <div className="mb-6">
    <Breadcrumb className="mb-4">
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbLink href="/dashboard" className="text-muted-foreground">
            Dashboard
          </BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator />
        <BreadcrumbItem>
          <BreadcrumbPage>Coupons & Dividends</BreadcrumbPage>
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>
    <CardTitle className="text-3xl font-bold">Coupons & Dividends</CardTitle>
    <CardDescription className="mt-2 text-lg">
      Analyze the cash flow generated by your investments.
    </CardDescription>
  </div>
);
export default Header;